### ISSUE TITLE
doesn't work with 2.1

### ISSUE THREAD

**Issue by Geniusssmit** [Kodeama/-Anki-Shinmeikai-Addon#3]
https://i.imgur.com/j3FHm9f.jpg

Just drag and drop "shinmeikai_definitions" from 2.1 from master branch into addons21, can't even start anki without error.
What should I do?

**Comment by Kodeama** [comment]
Hi @Geniusssmit, it seems like @shanrauf fixed the problem you are having. I merged his request so I think your problem will be fixed if you download the new version!
